services:
  terraform_backend:
    image: ghcr.io/nimbolus/terraform-backend
    build: .
    environment:
      STORAGE_FS_DIR: /states
      # change the key before using the backend
      KMS_KEY: jwS6UpASMOWpEmFn7C6I47BlmPt4cpdmYLKd2E7a4Zk=
      REDIS_ADDR: redis:6379
      LOCK_BACKEND: redis
    ports:
      - "8080:8080"
      - "127.0.0.1:8081:8081"
    volumes:
      - states:/states
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:RELEASE.2022-04-30T22-23-53Z # a version that still supports fs storage
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_CONSOLE_ADDRESS: :9001
    command: server /storage
    ports:
      - "9000:9000"
      - "9001:9001"
  openbao:
    image: ghcr.io/openbao/openbao
    command: server -dev -dev-root-token-id="dev-only-token"
    ports:
      - "8200:8200"
  openbao-init:
    image: ghcr.io/openbao/openbao
    volumes:
      - ./scripts/dev-openbao-init.sh:/dev-openbao-init.sh
    depends_on:
      - openbao
    entrypoint: /bin/sh
    command: /dev-openbao-init.sh dev-only-token
    environment:
      BAO_ADDR: http://openbao:8200
    restart: on-failure
    stop_grace_period: 100ms

volumes:
  states:
