[DEFAULT]
debug = False
log_file = /var/log/kolla/keystone/keystone.log
use_stderr = true

[database]
connection = mysql+pymysql://keystone:keystone@keystone-mysql:3306/keystone

[cache]
enabled = false

[auth]
methods = password,token,application_credential
